_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": train/images.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": global_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/bpp_y
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/images.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/images.format
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/images.caption
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/bpp_z
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/bpp_total
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/MSE
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/images.width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/images.height
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/images._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/images.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 7
                - 13
                - 16
                - 55
            "4": 3.11.0
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
architecture:
    value: AI Image Compression AutoEncoder
dataset:
    value: CLIC_2021
epochs:
    value: 2000
learning_rate:
    value: 0.0001
