_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 7
                - 13
                - 16
                - 55
            "4": 3.11.0
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
architecture:
    value: AI Image Compression AutoEncoder
dataset:
    value: CLIC_2021
epochs:
    value: 2000
learning_rate:
    value: 0.0001
